spring:
  application:
    name: microservice-demo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: ${MICRO_SERVICE_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true