spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-demo
          uri: lb://microservice-demo
          predicates:
            - Path=/microservice-demo/**
          filters:
            - PrefixPath=/api/v1

server:
  port: ${GATEWAY_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
